parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.

doctrine:
    dbal:
        connections:
            event:
                driver:   pdo_pgsql
                host:     "%env(DATABASE_HOST)%"
                port:     5432
                dbname:   poll_hq_event
                user:     dev
                password: dev
                charset:  utf8
                server_version: 11.2
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
            read:
                driver: pdo_pgsql
                host:     "%env(DATABASE_HOST)%"
                port:     5432
                dbname:   poll_hq_read
                user:     dev
                password: dev
                charset:  utf8
                server_version: 11.2
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
        types:
            datetime:        App\Adapter\Persistence\Doctrine\Type\DatetimeType
            event_stream_id: App\Adapter\Persistence\Doctrine\Type\EventStreamIdType
