framework:
    messenger:

        serializer:
            id: app.messenger.serializer

        buses:
            messenger.bus.command:
                middleware:
                    - messenger.middleware.validation
                    - app.messenger.bus.command.middleware.transaction

            messenger.bus.event:
                middleware:
                    - app.messenger.bus.event.middleware.transaction
                default_middleware: allow_no_handlers

        transports:
            amqp_commands:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange: {name: "commands", type: "fanout"}
                    queue: {name: "commands"}

            amqp_events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange: {name: "events", type: "fanout"}
                    queue: {name: "events"}

        routing:
            'App\Application\Command\Command': amqp_commands
            'Krixon\DomainEvent\Event': amqp_events
