twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    paths:
        "%kernel.project_dir%/templates":            view
        "%kernel.project_dir%/templates/_layouts":   layout
        "%kernel.project_dir%/templates/_partials":  partial
